services:

    php-fpm:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      restart: unless-stopped
      environment:
        COMPOSER_HOME: /var/www
        APP_ENV: ${APP_ENV}
        APP_DEBUG: ${APP_DEBUG}
      working_dir: /var/www
      mem_limit: 1024M
      mem_reservation: 128M
      volumes:
        - .:/var/www
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app-network

    db:
      image: mariadb
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      volumes:
        - db-database:/var/lib/mysql
        - ./initdb:/docker-entrypoint-initdb.d
      healthcheck:
        test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
        start_period: 5s
        interval: 10s
        timeout: 5s
        retries: 55
      networks:
        - app-network

    nginx:
      image: nginx
      restart: always
      tty: true
      ports: 
        - "3000:3000"
      volumes:
        - .:/var/www
        - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks: 
        - app-network
      depends_on:
        - php-fpm

networks: 
  app-network:
    driver: bridge

volumes:
    db-database: